"""add_chunking_methods_and_breakpoint_threshold_type

Revision ID: 683bc4c24582
Revises: 9ae2062eaac7
Create Date: 2025-11-07 13:50:33.980376

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "683bc4c24582"
down_revision: Union[str, None] = "9ae2062eaac7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create Enum types
    chunkingmethod = sa.Enum(
        "length", "semantic", "hybrid", "paragraph", name="chunkingmethod"
    )
    chunkingmethod.create(op.get_bind(), checkfirst=True)

    breakpointthresholdtype = sa.Enum(
        "percentile",
        "standard_deviation",
        "interquartile",
        name="breakpointthresholdtype",
    )
    breakpointthresholdtype.create(op.get_bind(), checkfirst=True)

    # Add new column
    op.add_column(
        "document",
        sa.Column(
            "breakpoint_threshold_type",
            breakpointthresholdtype,
            nullable=True,
            comment="시맨틱 청킹 전략 - 임계값 유형",
        ),
    )

    # Alter column with USING clause for type conversion
    op.alter_column(
        "document",
        "method",
        existing_type=sa.VARCHAR(),
        type_=chunkingmethod,
        existing_comment="청킹 전략 - 청크 방법",
        existing_nullable=True,
        postgresql_using="method::chunkingmethod",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "document",
        "method",
        existing_type=sa.Enum(
            "length", "semantic", "hybrid", "paragraph", name="chunkingmethod"
        ),
        type_=sa.VARCHAR(),
        existing_comment="청킹 전략 - 청크 방법",
        existing_nullable=True,
    )
    op.drop_column("document", "breakpoint_threshold_type")

    # Drop Enum types
    sa.Enum(name="chunkingmethod").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="breakpointthresholdtype").drop(
        op.get_bind(), checkfirst=True
    )
    # ### end Alembic commands ###
