"""create_graph_tables

Revision ID: 9ae2062eaac7
Revises: ba89c70aa082
Create Date: 2025-10-27 16:30:30.603912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ae2062eaac7'
down_revision: Union[str, None] = 'ba89c70aa082'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment='그래프 이름'),
    sa.Column('description', sa.String(), nullable=False, comment='그래프 설명'),
    sa.Column('version', sa.Integer(), nullable=False, comment='그래프 버전'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='삭제여부'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='생성일'),
    sa.Column('created_by', sa.String(), nullable=True, comment='생성자'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='수정일'),
    sa.Column('updated_by', sa.String(), nullable=True, comment='수정자'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_graph')),
    comment='그래프 테이블'
    )
    op.create_index(op.f('ix_graph_id'), 'graph', ['id'], unique=False)
    op.create_table('edge',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('graph_id', sa.CHAR(length=36), nullable=False, comment='그래프 아이디'),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('target', sa.String(length=100), nullable=False),
    sa.Column('condition', sa.JSON(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='삭제여부'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='생성일'),
    sa.Column('created_by', sa.String(), nullable=True, comment='생성자'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='수정일'),
    sa.Column('updated_by', sa.String(), nullable=True, comment='수정자'),
    sa.ForeignKeyConstraint(['graph_id'], ['graph.id'], name=op.f('fk_edge_graph_id_graph')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_edge')),
    comment='엣지 테이블'
    )
    op.create_index(op.f('ix_edge_graph_id'), 'edge', ['graph_id'], unique=False)
    op.create_index(op.f('ix_edge_id'), 'edge', ['id'], unique=False)
    op.create_table('graph_history',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('graph_id', sa.CHAR(length=36), nullable=False, comment='그래프 아이디'),
    sa.Column('input_state', sa.JSON(), nullable=False, comment='입력 상태'),
    sa.Column('output_state', sa.JSON(), nullable=True, comment='출력 상태'),
    sa.Column('status', sa.String(length=50), nullable=True, comment='상태'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='에러 메시지'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='삭제여부'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='생성일'),
    sa.Column('created_by', sa.String(), nullable=True, comment='생성자'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='수정일'),
    sa.Column('updated_by', sa.String(), nullable=True, comment='수정자'),
    sa.ForeignKeyConstraint(['graph_id'], ['graph.id'], name=op.f('fk_graph_history_graph_id_graph')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_graph_history')),
    comment='그래프 히스토리 테이블'
    )
    op.create_index(op.f('ix_graph_history_graph_id'), 'graph_history', ['graph_id'], unique=False)
    op.create_index(op.f('ix_graph_history_id'), 'graph_history', ['id'], unique=False)
    op.create_table('node',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('graph_id', sa.CHAR(length=36), nullable=False, comment='그래프 아이디'),
    sa.Column('node_id', sa.String(), nullable=False, comment='UI에서 사용하는 노드 아이디'),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('output', sa.String(length=100), nullable=True),
    sa.Column('position', sa.JSON(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='삭제여부'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='생성일'),
    sa.Column('created_by', sa.String(), nullable=True, comment='생성자'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='수정일'),
    sa.Column('updated_by', sa.String(), nullable=True, comment='수정자'),
    sa.ForeignKeyConstraint(['graph_id'], ['graph.id'], name=op.f('fk_node_graph_id_graph')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_node')),
    comment='그래프 테이블'
    )
    op.create_index(op.f('ix_node_graph_id'), 'node', ['graph_id'], unique=False)
    op.create_index(op.f('ix_node_id'), 'node', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_node_id'), table_name='node')
    op.drop_index(op.f('ix_node_graph_id'), table_name='node')
    op.drop_table('node')
    op.drop_index(op.f('ix_graph_history_id'), table_name='graph_history')
    op.drop_index(op.f('ix_graph_history_graph_id'), table_name='graph_history')
    op.drop_table('graph_history')
    op.drop_index(op.f('ix_edge_id'), table_name='edge')
    op.drop_index(op.f('ix_edge_graph_id'), table_name='edge')
    op.drop_table('edge')
    op.drop_index(op.f('ix_graph_id'), table_name='graph')
    op.drop_table('graph')
    # ### end Alembic commands ###
