"""remove_unique_constraint_from_collection_name

Revision ID: aae0b9688539
Revises: c1d2e3f4a5b6
Create Date: 2026-01-09 10:43:27.928117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aae0b9688539'
down_revision: Union[str, None] = 'c1d2e3f4a5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_collection_name', 'collection', type_='unique')
    op.alter_column('document', 'collection_id',
               existing_type=sa.CHAR(length=36),
               nullable=False,
               existing_comment='컬렉션 아이디')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'collection_id',
               existing_type=sa.CHAR(length=36),
               nullable=True,
               existing_comment='컬렉션 아이디')
    op.create_unique_constraint('uq_collection_name', 'collection', ['name'])
    # ### end Alembic commands ###
