"""Add RAG models (Document and Chunk)

Revision ID: b0f91ee7f793
Revises: 
Create Date: 2025-10-03 10:56:26.722491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0f91ee7f793'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment='문서 이름'),
    sa.Column('path', sa.String(), nullable=False, comment='문서 경로'),
    sa.Column('status', sa.Enum('pending', 'indexed', 'deleted', name='documentstatus'), nullable=True, comment='문서 상태'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='삭제여부'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='생성일'),
    sa.Column('created_by', sa.String(), nullable=True, comment='생성자'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='수정일'),
    sa.Column('updated_by', sa.String(), nullable=True, comment='수정자'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document')),
    comment='문서 테이블'
    )
    op.create_index(op.f('ix_document_id'), 'document', ['id'], unique=False)
    op.create_table('chunk',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('document_id', sa.CHAR(length=36), nullable=False, comment='문서 아이디'),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='청크 인덱스'),
    sa.Column('content', sa.Text(), nullable=False, comment='청크 내용'),
    sa.Column('embedding_id', sa.String(), nullable=True, comment='VectorDB key'),
    sa.Column('chunk_size', sa.Integer(), nullable=True, comment='청크 크기'),
    sa.Column('overlap_size', sa.Integer(), nullable=True, comment='청크 중복 크기'),
    sa.Column('method', sa.String(), nullable=True, comment='청크 방법'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='삭제여부'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='생성일'),
    sa.Column('created_by', sa.String(), nullable=True, comment='생성자'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='수정일'),
    sa.Column('updated_by', sa.String(), nullable=True, comment='수정자'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_chunk_document_id_document')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunk')),
    comment='청크 테이블'
    )
    op.create_index(op.f('ix_chunk_document_id'), 'chunk', ['document_id'], unique=False)
    op.create_index(op.f('ix_chunk_id'), 'chunk', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunk_id'), table_name='chunk')
    op.drop_index(op.f('ix_chunk_document_id'), table_name='chunk')
    op.drop_table('chunk')
    op.drop_index(op.f('ix_document_id'), table_name='document')
    op.drop_table('document')
    # ### end Alembic commands ###
