"""alter_table

Revision ID: ba89c70aa082
Revises: b0f91ee7f793
Create Date: 2025-10-03 16:32:49.996860

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ba89c70aa082"
down_revision: Union[str, None] = "b0f91ee7f793"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chunk",
        "chunk_size",
        existing_type=sa.INTEGER(),
        comment="실제 청크 크기",
        existing_comment="청크 크기",
        existing_nullable=True,
    )
    op.drop_column("chunk", "method")
    op.drop_column("chunk", "overlap_size")
    op.add_column(
        "document",
        sa.Column(
            "chunk_size",
            sa.Integer(),
            nullable=True,
            comment="청킹 전략 - 청크 크기",
        ),
    )
    op.add_column(
        "document",
        sa.Column(
            "overlap_size",
            sa.Integer(),
            nullable=True,
            comment="청킹 전략 - 청크 중복 크기",
        ),
    )
    op.add_column(
        "document",
        sa.Column(
            "method",
            sa.String(),
            nullable=True,
            comment="청킹 전략 - 청크 방법",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document", "method")
    op.drop_column("document", "overlap_size")
    op.drop_column("document", "chunk_size")
    op.add_column(
        "chunk",
        sa.Column(
            "overlap_size",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="청크 중복 크기",
        ),
    )
    op.add_column(
        "chunk",
        sa.Column(
            "method",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
            comment="청크 방법",
        ),
    )
    op.alter_column(
        "chunk",
        "chunk_size",
        existing_type=sa.INTEGER(),
        comment="청크 크기",
        existing_comment="실제 청크 크기",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
