"""add_collection_table_and_document_fk

Revision ID: c1d2e3f4a5b6
Revises: 683bc4c24582
Create Date: 2025-11-10 00:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c1d2e3f4a5b6"
down_revision: Union[str, None] = "683bc4c24582"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Collection 테이블 생성
    op.create_table(
        "collection",
        sa.Column("id", sa.CHAR(length=36), nullable=False),
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
            comment="컬렉션 이름",
        ),
        sa.Column(
            "description",
            sa.String(length=500),
            nullable=True,
            comment="컬렉션 설명",
        ),
        sa.Column(
            "is_deleted", sa.Boolean(), nullable=True, comment="삭제여부"
        ),
        sa.Column(
            "created_at", sa.DateTime(), nullable=True, comment="생성일"
        ),
        sa.Column("created_by", sa.String(), nullable=True, comment="생성자"),
        sa.Column(
            "updated_at", sa.DateTime(), nullable=True, comment="수정일"
        ),
        sa.Column("updated_by", sa.String(), nullable=True, comment="수정자"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collection")),
        sa.UniqueConstraint("name", name=op.f("uq_collection_name")),
        comment="컬렉션 테이블",
    )
    op.create_index(
        op.f("ix_collection_id"), "collection", ["id"], unique=False
    )

    # 2. Document 테이블에 collection_id 컬럼 추가 (nullable=True로 먼저 추가)
    op.add_column(
        "document",
        sa.Column(
            "collection_id",
            sa.CHAR(length=36),
            nullable=True,
            comment="컬렉션 아이디",
        ),
    )

    # 3. collection_id에 인덱스 추가
    op.create_index(
        op.f("ix_document_collection_id"),
        "document",
        ["collection_id"],
        unique=False,
    )

    # 4. Foreign Key 제약 조건 추가
    op.create_foreign_key(
        op.f("fk_document_collection_id_collection"),
        "document",
        "collection",
        ["collection_id"],
        ["id"],
    )

    # 5. 기본 컬렉션 데이터 삽입 (기존 문서들을 위해)
    # 이 부분은 선택사항이며, 기존 문서가 있는 경우 필요
    # op.execute(
    #     """
    #     INSERT INTO collection (id, name, description, is_deleted, created_at, created_by, updated_at, updated_by)
    #     VALUES (
    #         UUID(),
    #         'default',
    #         '기본 컬렉션',
    #         FALSE,
    #         NOW(),
    #         'system',
    #         NOW(),
    #         'system'
    #     )
    #     """
    # )

    # 6. 기존 문서들의 collection_id를 기본 컬렉션으로 업데이트
    # op.execute(
    #     """
    #     UPDATE document
    #     SET collection_id = (SELECT id FROM collection WHERE name = 'default')
    #     WHERE collection_id IS NULL
    #     """
    # )

    # 7. collection_id를 NOT NULL로 변경 (기존 데이터 마이그레이션 후)
    # op.alter_column(
    #     "document",
    #     "collection_id",
    #     existing_type=sa.CHAR(length=36),
    #     nullable=False,
    #     existing_comment="컬렉션 아이디",
    # )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Foreign Key 제약 조건 제거
    op.drop_constraint(
        op.f("fk_document_collection_id_collection"),
        "document",
        type_="foreignkey",
    )

    # 2. collection_id 인덱스 제거
    op.drop_index(op.f("ix_document_collection_id"), table_name="document")

    # 3. Document 테이블에서 collection_id 컬럼 제거
    op.drop_column("document", "collection_id")

    # 4. Collection 테이블 인덱스 제거
    op.drop_index(op.f("ix_collection_id"), table_name="collection")

    # 5. Collection 테이블 제거
    op.drop_table("collection")
    # ### end Alembic commands ###
